masterpiece/views/auth_views.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, session, g
from werkzeug.security import generate_password_hash, check_password_hash

from masterpiece import db

from masterpiece.forms import UserCreateForm, UserLoginForm
from masterpiece.models import User

import functools

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/create/', methods=('GET', 'POST'))
def create():
    form = UserCreateForm()
    if request.method=='POST' and form.validate_on_submit():
        user = User.query.filter_by(user_name=form.user_name.data).first()
        user_id = User.query.filter_by(user_email_id=form.user_email_id.data).first()
        if not user and not user_id:
            user = User(user_email_id=form.user_email_id.data, user_name=form.user_name.data, password=generate_password_hash(form.password1.data))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('main.index'))
        elif user and not user_id:
            flash('이미 존재하는 사용자명입니다.')
        elif not user and user_id:
            flash('이미 존재하는 아이디입니다.')
        else:
            flash('이미 존재하는 사용자명이며 아이디입니다')
    return render_template('auth_create.html', form=form)

@bp.route('/login/', methods=('GET', 'POST'))
def login():
    form = UserLoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(user_email_id=form.user_email_id.data).first()
        if not user:
            flash('존재하지 않는 ID입니다')
        elif not check_password_hash(user.password, form.password.data):
            flash('ID는 존재하나 비밀번호가 일치하지 않습니다')
        else:
            session.clear()
            session['user_id'] = user.id
            _next = request.args.get('next', '')
            if _next:
                return redirect(_next)
            else:
                return redirect(url_for('main.index'))
    return render_template('auth_login.html', form=form)

@bp.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('main.index'))

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')
    if user_id is None:
        g.user = None
    else:
        g.user = User.query.get(user_id)

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(*args, **kwargs):
        if g.user is None:
            _next = request.url if request.method == 'GET' else ''
            return redirect(url_for('auth.login', next=_next))
        return view(*args, **kwargs)
    return wrapped_view

masterpiece/views/review_views.py
from masterpiece.forms import ReviewForm
from flask import Blueprint, render_template, request, redirect, url_for, session, flash, g
from datetime import datetime
import math

from masterpiece import db

from masterpiece.models import Song, Review, User

from .auth_views import login_required

bp = Blueprint('review', __name__, url_prefix='/review')

@bp.route('/add/<int:song_id>', methods=('GET', 'POST'))
@login_required
def add(song_id):
    form = ReviewForm()
    song = Song.query.get(song_id)
    if g.user.user_name in [review.user_name for review in song.review_set]:
        flash('이미 후기를 작성하였습니다.')
        return render_template('errors.html', song_id=song_id)
    elif request.method=="POST":
        if form.validate_on_submit():
            user_name = User.query.get(session['user_id']).user_name
            review = Review(song_id=song_id, rate=form.rate.data, content=form.content.data, user_name=user_name, write_date=datetime.now())
            db.session.add(review)
            db.session.commit()
            #노래 평균평점 자동계산
            if not song.average_rate: #노래 평균평점이 None일 경우 0으로 세팅
                song.average_rate = 0
            review_count = len(song.review_set)
            song.average_rate = ((review_count-1) * song.average_rate + form.rate.data) / review_count
            db.session.commit()
            update_song_score()  # 마스터피스 점수 업데이트
            return redirect(url_for('song.detail', song_id=song_id))
    else:
        return render_template("review_add.html", form=form,song=song)

@bp.route('/delete/<int:review_id>')
@login_required
def delete(review_id):
    review = Review.query.get_or_404(review_id)
    song_id = review.song.id
    song = Song.query.get(song_id)
    if g.user.user_name != review.user_name:
        flash('삭제권한이 없습니다.')
    else:
        #노래 평균평점 자동계산
        review_count = len(song.review_set)
        song.average_rate = ((review_count) * song.average_rate - review.rate) / (review_count-1)
        db.session.delete(review)
        db.session.commit()
        update_song_score()  # 마스터피스 점수 업데이트
    return redirect(url_for('song.detail', song_id=song_id))

@bp.route('/edit/<int:review_id>', methods=('GET', 'POST'))
@login_required
def edit(review_id):
    review = Review.query.get_or_404(review_id)
    if g.user.user_name != review.user_name:
        flash('수정권한이 없습니다')
    elif request.method=="POST":
        form = ReviewForm()
        if form.validate_on_submit():
            form.populate_obj(review)
            #노래 평균평점 자동계산
            song = Song.query.get(review.song.id)
            review_count = len(song.review_set)
            song.average_rate = ((review_count) * song.average_rate -session['previous_rate'] + review.rate) / (review_count)
            db.session.commit()
            update_song_score()  # 마스터피스 점수 업데이트
            return redirect(url_for('song.detail', song_id=review.song.id))
    else:
        form = ReviewForm(obj=review)
        session['previous_rate']=review.rate
        return render_template('review_add.html', form=form)
    
def update_song_score(*args):
    # 모든 Song 인스턴스에 대해 score 값을 업데이트
    total_reviews = Review.query.count()
    total_song_with_reviews = Song.query.join(Review).distinct().count()
    all_songs = Song.query.all()
    for song in all_songs:
        if song.average_rate:
            total_reviews_in_song = len(song.review_set)
            alpha = total_reviews_in_song / total_reviews - 1 / total_song_with_reviews
            flag = 1 if alpha>0 else -1
            if alpha == 0: #알파가 0이면 정규화가 불가능(거듭제곱이 불가함)하므로 예외처리
                normalized_alpha = 0
            else: #알파 정규화
                normalized_alpha = (abs(alpha)**math.log(total_reviews_in_song)) * flag
            score = song.average_rate + normalized_alpha
            song.masterpiece_score = score
            print(f"Song name:{song.name}, alpha:{alpha}, normalized_alpha:{normalized_alpha}")
            db.session.add(song)
            db.session.commit()

masterpiece/views/song_views.py
from flask import Blueprint, url_for, render_template, request, session
from werkzeug.utils import redirect
from sqlalchemy import func, desc
from datetime import datetime

from masterpiece import db
from masterpiece.models import Song, Review, User
from masterpiece.forms import SongForm, ReviewForm
from .auth_views import login_required

import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pprint
 
cid = '1c2246a49faf498eb364c3867ddf912f'
secret = 'fbe55a0277f04533a9fa88012a9d5a9f'
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
 
sp = spotipy.Spotify(client_credentials_manager=client_credentials_manager)

bp = Blueprint('song', __name__, url_prefix='/song')

@bp.route('/')
def _list():
    page = request.args.get('page', type=int, default=1)  # 페이지
    kw = request.args.get('kw', type=str, default='') # 검색어

    songs = db.session.query(Song).all()
    songs_spotify_id = [song.spotify_id for song in songs]

    # 최근 리뷰가 등록된 순서로 정렬하여 song_list에 가장 최근의 리뷰날짜와 함께 저장
    query = (db.session.query(Song.id, Song.spotify_id, Song.name, Song.singer, Song.average_rate, Song.masterpiece_score, Song.image_url, func.count(Review.id), Review.write_date).join(Review).group_by(Song.id).having(Review.write_date == func.max(Review.write_date)).order_by(desc(Review.write_date)))
    song_list = query.paginate(page=page, per_page=5)

    # 자체 음악 랭킹 기준으로 정렬하여 song_ranking에 저장
    song_ranking = (db.session.query(Song).filter(Song.average_rate != None).order_by(desc(Song.masterpiece_score)))

    if kw:
        search = sp.search(q=kw, limit=50, type="track", market='KR')
        return render_template("song_list.html", songs=songs, songs_spotify_id=songs_spotify_id, song_list=song_list, song_ranking=song_ranking, search=search)
    else:
        return render_template("song_list.html", song_list=song_list, song_ranking=song_ranking)

@bp.route('/ranking/')
def ranking():
    page = request.args.get('page', type=int, default=1)  # 페이지

    # 자체 음악 랭킹 기준으로 정렬하여 song_ranking에 저장
    song_ranking = (db.session.query(Song).filter(Song.average_rate != None).order_by(desc(Song.masterpiece_score)))
    song_ranking = song_ranking.paginate(page=page, per_page=10)

    return render_template("song_ranking.html", song_ranking=song_ranking, page=page)


@bp.route('/detail/<int:song_id>/')
def detail(song_id):
    song = Song.query.get(song_id)
    return render_template("song_detail.html", song=song)

@bp.route('/add/')
@login_required
def add():
    spotify_id = request.args.get('spotify_id', type=str)
    name = request.args.get('name', type=str)
    singer = request.args.get('singer', type=str)
    image_url = request.args.get('image_url', type=str)
    spotify_url = request.args.get('spotify_url', type=str)
    if spotify_id and name and singer and image_url:
        song = Song(spotify_id=spotify_id, name=name, singer=singer, image_url=image_url, average_rate=None, spotify_url=spotify_url)
        db.session.add(song)
        db.session.commit()
        added_song = Song.query.order_by(Song.id.desc()).first()
        return redirect(url_for('song.detail', song_id=added_song.id))
    return render_template("base.html") #오류나면 베이스템플릿만 출력

masterpiece/templates/auth_create.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
    <!--오류표시 start-->
    {% if form.errors %}
    <div>
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    <!--오류표시 end-->
    {{ form.csrf_token }}

    <div>
        <lable for="user_email_id">아이디(이메일형식)</lable>
        <input type="text" class="form=control" name="user_email_id" id="user_email_id"
            value="{{ form.user_email_id.data or '' }}">
    </div>
    <div>
        <lable for="user_name">닉네임</lable>
        <input type="text" class="form=control" name="user_name" id="user_name"
            value="{{ form.user_name.data or '' }}">
    </div>
    <div>
        <lable for="user_password1">비밀번호</lable>
        <input type="password" class="form=control" name="password1" id="password1"
            value="{{ form.password1.data or '' }}">
    </div>
    <div>
        <lable for="user_password2">비밀번호 확인</lable>
        <input type="password" class="form=control" name="password2" id="password2"
            value="{{ form.password2.data or '' }}">
    </div>
    <button type="submit" class="btn btn-primary">회원가입하기</button>
</form>
{% endblock %}

masterpiece/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta name="naver-site-verification" content="f7102641c71c5c323d13d2fbff702e19880337bd" />
    <meta name="google-site-verification" content="CcxJTIYriCC3TdNthDf6ijl8qg255bypD3GueNGNNuU" />
    <meta name="description" content="국내 음반 평점/후기">
    <meta property="og:type" content="website"> 
    <meta property="og:title" content="MasterPiece 마스터피스">
    <meta property="og:description" content="국내 음반 평점/후기">
    <meta property="og:image" content="https://i.ibb.co/HPR1jg7/masterpiece.png">
    <meta property="og:url" content="http://masterp.site">

    <link rel="shortcut icon" href="https://i.ibb.co/HPR1jg7/masterpiece.png">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MasterPiece</title>
    <style>
        .song-container {
            display: flex;
            flex-wrap: nowrap;
            overflow-x: auto;
        }
        .song-item {
            margin: 10px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
            border-radius: 5px;
            min-width: 150px;
            text-align: center;
        }
        .song-item img {
            display: block;
            margin: 0 auto 10px;
        }
        .pagination-container {
            display: flex;
            justify-content: center;
            margin-top: 20px;
        }
        .pagination {
            display: flex;
            flex-wrap: nowrap;
            overflow-x: auto;
        }
        .pagination .page-item {
            margin: 0 5px;
            flex: 0 0 auto;
        }
        .pagination .page-item a {
            display: block;
            padding: 5px 10px;
            border-radius: 5px;
            text-decoration: none;
            color: black;
        }
        .pagination .page-item.active a {
            background-color: #007bff;
            color: white;
        }
        .pagination .page-item.disabled a {
            color: #6c757d;
        }
    </style>
</head>
<body>
    <a href="{{ url_for('main.index') }}">
        <img src="https://i.ibb.co/HPR1jg7/masterpiece.png" width="55" height="55">
    </a>
        <font size=7>마스터피스 - 국내 음반 평점/후기</font><br>
    {% if g.user %}
        <a href="{{ url_for('auth.logout') }}">로그아웃({{ g.user.user_name }})</a>
    {% else %}
        <a href="{{ url_for('auth.login') }}">로그인</a>
        <a href="{{ url_for('auth.create') }}">회원가입</a>
    {% endif %}
    <br>---------------------------------------<br>
    {% block content %}
    {% endblock %}
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

masterpiece/templates/errors.html
 <!-- flash 오류 -->
 {% for message in get_flashed_messages() %}
 <div class="alert alert-danger" role="alert">
     {{ message }}
 </div>
 {% endfor %}
 <a href="{{ url_for('song.detail',song_id=song_id) }}">원래 페이지로 돌아가기</a>

masterpiece/templates/song_detail.html
{% extends 'base.html' %}
{% block content %}
<img src="{{ song.image_url }}" width="200" height="200"><br>
{{ song.name }} - {{ song.singer }}<br>
평균★{{ song.average_rate|round2 }}<br>
마스터피스 스코어 {{ song.masterpiece_score }}<br>
<a href="{{ song.spotify_url }}"><img src="https://cdn.icon-icons.com/icons2/3041/PNG/512/spotify_logo_icon_189218.png" width="50" height="50"></a>
<br>
----------------------------------------------------<br>
<후기/평점>
<br><br>
{% for review in song.review_set %}
{% if g.user.user_name==review.user_name %}
[내 후기 및 평점]<br> {{ review.content }} - ★{{ review.rate }}
<a href="{{ url_for('review.edit', review_id=review.id) }}">후기 수정</a>
<a href="" class="delete" data-uri="{{ url_for('review.delete', review_id=review.id) }}">후기 삭제</a>
<br><br>
{% endif %}
{% endfor %}

{% for review in song.review_set %}
- {{ review.content }} - ★{{ review.rate }}     ({{ review.user_name }}에 의해 {{ review.write_date|datetime }}에 작성됨)
<br><br>
{% endfor %}

{% if not song.review_set %}
아직 등록된 후기가 없습니다.<br><br>
{% endif %}

{% if not g.user.user_name in song.review_set|map(attribute='user_name') %}
    <a href="{{ url_for('review.add', song_id=song.id) }}">평점 부여하고 후기 작성하기</a><br>
{% endif %}
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}

masterpiece/templates/song_list.html
{% extends 'base.html' %}
{% block content %}
<div class="input-group">
    <img src="https://upload.wikimedia.org/wikipedia/commons/7/75/Spotify_icon.png" width="20" height="20">
    <input type="text" id="search_kw" class="form-control" value="{{ kw or '' }}">
    <button class="btn btn-outline-secondary" type="button" id="btn_search">검색</button>
    <br>노래를 검색해 새로운 후기를 등록할 수 있습니다.<br>
</div>
---------------------------------------
<br>
<!-- 검색결과 출력 시작 -->
{% if search %}
<div class="song-container">
    {% for i in range(50) %}
    {% if search['tracks']['items'][i] %}
    <!-- 검색한 노래의 id가 Song모델의 인스턴스 중 spotify_id속성에 있으면 -->
    {% if search['tracks']['items'][i]['id'] in songs_spotify_id %} 
    {% for song in songs %}
    {% if search['tracks']['items'][i]['id'] == song.spotify_id %}
    <div class="song-item">
        <a href="{{ url_for('song.detail', song_id=song.id) }}">{{ song.name }} - {{ song.singer }}</a><br>  평균★{{ song.average_rate|round2 }}/5.0<br>  평가수 {{ song[7] }}
        <img src="{{ search['tracks']['items'][i]['album']['images'][0]['url'] }}" width="100" height="100"><br>
    </div>
    {% endif %}
    {% endfor %}
    <!-- 검색한 노래의 id가 Song모델의 인스턴스 중 spotify_id속성에 없으면 -->
    {% else %}
    {% if search['tracks']['items'][i]['album']['images'][0] %}
    <div class="song-item">
        <a href="{{ url_for('song.add', spotify_id=search['tracks']['items'][i]['id'], name=search['tracks']['items'][i]['name'], singer=search['tracks']['items'][i]['artists'][0]['name'], image_url=search['tracks']['items'][i]['album']['images'][0]['url'], spotify_url=search['tracks']['items'][i]['external_urls']['spotify']) }}">{{ search['tracks']['items'][i]['name'] }}, {{ search['tracks']['items'][i]['artists'][0]['name'] }}</a><br>
        평균★None/5.0(아직 평가되지 않았습니다)<br>
        평가수 0<br>
        <img src="{{ search['tracks']['items'][i]['album']['images'][0]['url'] }}" width="100" height="100"><br>
    </div>
    {% endif %}
    {% endif %}
    {% endif %}
    {% endfor %}
</div>
<!-- 검색결과 출력 끝 -->
{% else %}
<!-- 최근 평가된 노래순서로 출력 시작 -->
{% if song_list %}
[Recent Rated Musics]
<div class="song-container">
    {% for song in song_list.items %}
    <div class="song-item">
        <a href="{{ url_for('song.detail', song_id=song.id) }}">{{ song.name }} - {{ song.singer }}</a><br>  평균★{{ song.average_rate|round2 }}/5.0<br>  평가수 {{ song[7] }}<br>
        <img src="{{ song.image_url }}" width="100" height="100"><br>
    </div>
    {% endfor %}
</div>
{% endif %}
<!-- 최근 평가된 노래순서로 출력 끝 -->

<!-- 페이징처리 시작 -->
<div class="pagination-container">
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if song_list.has_prev %}
        <li class="page-item" style="list-style: none;">
            <a class="page-link" data-page="{{ song_list.prev_num }}" href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled" style="list-style: none;">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지번호 -->
        {% for page_num in song_list.iter_pages() %}
        {% if page_num %}
        {% if page_num != song_list.page %}
        <li class="page-item" style="list-style: none;">
            <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% else %}
        <li class="page-item active" aria-current="page" style="list-style: none;">
            <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li class="page-item disabled" style="list-style: none;">
            <a class="page-link" href="javascript:void(0)">...</a>
        </li>
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if song_list.has_next %}
        <li class="page-item" style="list-style: none;">
            <a class="page-link" data-page="{{ song_list.next_num }}" href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled" style="list-style: none;">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
<!-- 페이징처리 끝 -->
<br>
<!-- 마스터피스 랭킹 순서로 노래 출력 시작 -->
{% if song_ranking %}
[MasterPiece Ranking]
<div class="song-container">
    {% for song in song_ranking %}
    {% if 5 >= loop.index %}
    <div class="song-item">
        마스터피스 랭킹 '{{ loop.index }}위'<br>
        <a href="{{ url_for('song.detail', song_id=song.id) }}">{{ song.name }} - {{ song.singer }}</a><br>  평균★{{ song.average_rate|round2 }}/5.0<br>  평가수 {{ song.review_set|length }}<br>
        <img src="{{ song.image_url }}" width="100" height="100"><br>
    </div>
    {% endif %}
    {% if loop.index == 6 %}
    <button id="btn_more">더보기</button>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
<!-- 마스터피스 랭킹 순서로 노래 출력 끝 -->
{% endif %}

<form id="searchForm" method="get" action="{{ url_for('song._list') }}">
    <input type="hidden" id="kw" name="kw" value="{{ kw or '' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('searchForm').submit();
});
</script>
<script>
document.getElementById("btn_more").addEventListener("click", function() {
    window.location.href = "{{ url_for('song.ranking') }}";
});
</script>
<!-- 광고 시작 -->
<ins class="kakao_ad_area" style="display:none;"
data-ad-unit = "DAN-WfCK5UJjdsQwb3mx"
data-ad-width = "300"
data-ad-height = "250"></ins>
<script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>

<ins class="kakao_ad_area" style="display:none;"
data-ad-unit = "DAN-vLlElnaWlEIrlkbl"
data-ad-width = "300"
data-ad-height = "250"></ins>
<script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>

<ins class="kakao_ad_area" style="display:none;"
data-ad-unit = "DAN-8r1Wi8Q0DTtSB0BU"
data-ad-width = "300"
data-ad-height = "250"></ins>
<script type="text/javascript" src="//t1.daumcdn.net/kas/static/ba.min.js" async></script>
<!-- 광고 끝-->
{% endblock %}

{% block styles %}
<style>
    .song-container {
        display: flex;
        flex-wrap: nowrap;
        overflow-x: auto;
        white-space: nowrap;
    }
    .song-item {
        display: inline-block;
        width: 200px;
        height: auto;
        margin: 10px;
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        background-color: #f9f9f9;
        text-align: center;
    }
    .pagination-container ul.pagination {
        display: flex;
        flex-wrap: nowrap;
        padding-left: 0;
        list-style-type: none;
    }
    .pagination-container ul.pagination li.page-item {
        margin: 0 5px;
    }
    .pagination-container ul.pagination li.page-item a.page-link {
        padding: 5px 10px;
        text-decoration: none;
        color: black;
        background-color: white;
        border: 1px solid #dee2e6;
        border-radius: 3px;
    }
    .pagination-container ul.pagination li.page-item.active a.page-link {
        background-color: #007bff;
        color: white;
    }
    .pagination-container ul.pagination li.page-item.disabled a.page-link {
        color: #6c757d;
        pointer-events: none;
    }
    .pagination justify-content-center {
        list-style-type: none;
    }
</style>
{% endblock %}

masterpiece/templates/song_ranking.html
{% extends 'base.html' %}
{% block content %}
<!-- 마스터피스 랭킹 순서로 노래 출력 시작 -->
{% if song_ranking %}
[MasterPiece Ranking]<br>
마스터피스 랭킹은 평균평점과 평가수 등을 자체 내장 함수를 통해 종합해 랭킹을 매기는 시스템입니다. 
    <ul>
        {% for song in song_ranking.items %}
        <li>
            마스터피스 랭킹 '{{ (page-1)*10 + loop.index }}위'<br>
            <a href="{{ url_for('song.detail', song_id=song.id) }}">{{ song.name }} - {{ song.singer }}</a>
            <br>  평균★{{ song.average_rate|round2 }}/5.0<br>  평가수 {{ song.review_set|length }}<br>
            마스터피스 스코어 {{ song.masterpiece_score }}<br>
            <img src="{{ song.image_url }}" width="100" height="100"><br>
        </li>
        <br>
        {% endfor %}
    </ul>
{% endif %}
<!-- 마스터피스 랭킹 순서로 노래 출력 끝 -->

<!-- 페이징처리 시작 -->
<ul class="pagination justify-content-center">
    <!-- 이전페이지 -->
    {% if song_ranking.has_prev %}
    <li class="page-item" style="list-style: none;">
        <a class="page-link" data-page="{{ song_ranking.prev_num }}" href="javascript:void(0)">이전</a>
    </li>
    {% else %}
    <li class="page-item disabled" style="list-style: none;">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
    </li>
    {% endif %}
    <!-- 페이지번호 -->
    {% for page_num in song_ranking.iter_pages() %}
    {% if page_num %}
    {% if page_num != song_ranking.page %}
    <li class="page-item" style="list-style: none;">
        <a class="page-link" data-page="{{ page_num }}" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% else %}
    <li class="page-item active" aria-current="page" style="list-style: none;">
        <a class="page-link" href="javascript:void(0)">{{ page_num }}</a>
    </li>
    {% endif %}
    {% else %}
    <li class="disabled" style="list-style: none;">
        <a class="page-link" href="javascript:void(0)">...</a>
    </li>
    {% endif %}
    {% endfor %}
    <!-- 다음페이지 -->
    {% if song_ranking.has_next %}
    <li class="page-item" style="list-style: none;">
        <a class="page-link" data-page="{{ song_ranking.next_num }}" href="javascript:void(0)">다음</a>
    </li>
    {% else %}
    <li class="page-item disabled" style="list-style: none;">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
    </li>
    {% endif %}
</ul>
<form id="pageForm" method="get" action="{{ url_for('song.ranking') }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
<br><br>
{% endblock %}

{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('pageForm').submit();
    });
});
</script>
{% endblock %}